### ISSUE TITLE
Ubuntu 24.04 LTS failing install

### ISSUE THREAD

**Issue by jaribeckman** [rsyslog/rsyslog-pkg-ubuntu#173] opened 2024-08-27 12:08 UTC
Hello, using cloud image for Ubuntu 24.04 LTS. Trying to install from latest v8-stable repo but kept failing even after removing and deleting files and retrying. Suspecting some corrupt file or typo. For now switched to daily developer repo instead which installs fine.

ubuntu@syslog01:~$ sudo apt-get -y install rsyslog
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Suggested packages:
  rsyslog-mysql | rsyslog-pgsql rsyslog-doc rsyslog-relp rsyslog-elasticsearch rsyslog-mmjsonparse
  rsyslog-imptcp rsyslog-gnutls rsyslog-openssl rsyslog-udpspoof rsyslog-mmrm1stspace rsyslog-mmutf8fix
  rsyslog-kafka rsyslog-omstdout
The following NEW packages will be installed:
  rsyslog
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 778 kB of archives.
After this operation, 1976 kB of additional disk space will be used.
Get:1 https://ppa.launchpadcontent.net/adiscon/v8-stable/ubuntu noble/main amd64 rsyslog amd64 8.2408.0-0adiscon1                                                                noble1 [778 kB]
Fetched 778 kB in 0s (1587 kB/s)
(Reading database ... 71867 files and directories currently installed.)
Preparing to unpack .../rsyslog_8.2408.0-0adiscon1noble1_amd64.deb ...
Unpacking rsyslog (8.2408.0-0adiscon1noble1) ...
dpkg: error processing archive /var/cache/apt/archives/rsyslog_8.2408.0-0adiscon1noble1_amd64.deb (--unpack):
 unable to open '/usr/lib/systemd/system/rsyslog.service.dpkg-new': No such file or directory
No apport report written because the error message indicates an issue on the local system
                                                                                         Errors were encountered                                                                 while processing:
 /var/cache/apt/archives/rsyslog_8.2408.0-0adiscon1noble1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by AnSPetrov** [comment] 2024-08-28 15:23
Same problem. I can try install from ppa:adiscon/daily-stable but noble series doesnt supported. How were you able to achieve a successful installation?

**Comment by friedl** [comment] 2024-08-28 20:30
We are already aware of the issue with the failing install on Ubuntu 24.04 and investigating. 

There seems to be an issue with the package building process for the stable packages. For the time being, the issue is marked as a bug.

**Comment by useful64** [comment] 2024-09-12 14:27
It seems that the rsyslog.service file is duplicated. If you delete it, it works:
```
dpkg -x /var/cache/apt/archives/rsyslog_8.2408.0-0adiscon5noble1_amd64.deb ./rsyslog
mkdir ./rsyslog/DEBIAN
dpkg --control /var/cache/apt/archives/rsyslog_8.2408.0-0adiscon5noble1_amd64.deb ./rsyslog/DEBIAN/
rm ./rsyslog/lib/systemd/system/rsyslog.service
rmdir ./rsyslog/lib/systemd/system/
rmdir ./rsyslog/lib/systemd/
rmdir ./rsyslog/lib/
dpkg -b ./rsyslog/ /tmp/rsyslog.deb
sudo apt install /tmp/rsyslog.deb
```

Also I have problems with Apparmor and with the file "/usr/lib/rsyslog/reload-apparmor-profile" as it does not exist and I had to get the files from Ubuntu package.

**Comment by fukawi2** [comment] 2024-10-16 23:45
This is blocking our upgrade to 24.04 - is there an ETA for this, or something we can do to help resolve?

**Comment by GZRad** [comment] 2024-10-24 15:04
Same here. Ubuntu isn't providing the modules I need (mmnormalize, imudp, imtcp) & I can't just compile the stuff myself.

**Comment by friedl** [comment] 2024-10-24 16:11
There is currently still an issue with our build environment and this build in particular. We hope to have it up and running soon. Until then, I can only tell you that we are working on it. We want this out of the door as much as anyone else.

**Comment by alorbach** [comment] 2024-11-04 12:35
I am sorry for the delay, we had to rebuild the noble package files from scratch as the differences between ours and Ubuntu base packages have been grown to much. 

Please see also https://github.com/rsyslog/rsyslog-pkg-ubuntu/pull/178

New Packages for noble have been deployed on our launchpad.

**Closed** 2024-11-05 12:18 UTC
Labels: bug

**Comment by fukawi2** [comment] 2024-11-06 00:19
Thanks @alorbach - appreciate your efforts :)

**Comment by GZRad** [comment] 2024-11-06 10:08
Many thanks, much appreciated. Confirmed as working on my end.
